# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29ca4b376431de96883782d29d7dab9683fd9bc5c825690dc700abeca21711cbb9a94732fb195f20aeb767f9de5aff66a68cbee2f0b0376341c2a739cc6f7e60

test:
  secret_key_base: f365bbd1073e81b46d6c513cc5487c0cf060d9c8a7e0995cc27fc8670faa7d719948dd53b0d87ad86eb3fe6cdcf9dfaeeee9d11a0d43ff92a06d39594ef6b657

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
